### ISSUE TITLE
non-numeric (e.g. uuid) id breaks queryset_iterator

### ISSUE THREAD

**Issue by zorba-the-geek** [jaddison/django-simple-elasticsearch#18]
queryset_iterator in utils.py relies on an int primary key. Having a uuid primary key breaks it, which prevents rebuilding indices. 

For now I have changed line 74 mixins.py commit fb13b30 from:
`for i, obj in enumerate(queryset_iterator(queryset, cls.get_query_limit())):`
to:
`for i, obj in enumerate(queryset):`

And that works. FYI I am new to this whole elasticsearch thing.

**Comment by jaddison** [comment]
Indeed, I should probably look to improve that level of compatibility. Pull requests are welcome, of course.

Note that what you're doing in your fix above will likely exhaust the server's memory as it will retrieve all records and load them into memory at once in preparation for iteration.

**Comment by yakky** [comment]
@jaddison same issue here. Why not just using slicing? Some thing like appears to work:
```
def queryset_iterator(queryset, chunksize=1000):
    total = queryset.count()
    queryset = queryset.order_by('pk')
    for start in range(0, total, chunksize):
        for row in queryset[start:chunksize]:
            yield row
        gc.collect()
```

**Comment by jaddison** [comment]
```
def queryset_iterator(queryset, chunksize=1000):
    try:
        last_pk = queryset.order_by('-pk')[0].pk
    except IndexError:
        return

    queryset = queryset.order_by('pk')
    pk = queryset[0].pk - 1
    while pk < last_pk:
        for row in queryset.filter(pk__gt=pk)[:chunksize]:
            pk = row.pk
            yield row
        gc.collect()
```
Took a few minutes to refresh my memory here - so, given the existing `queryset_iterator` function above:

I **think** why I wrote it this way was to catch new records that were written since the reindex process was started.

Generally, the big problem with reindexing data into a new index and tossing the old index is ensuring that new AND updated records are properly indexed. With an auto-incrementing PK, it's easy enough to grab the most recently added files (which is what my code is attempting to do, I believe) - but there is probably a better way to do it for auto-incrementing PKs. 

Using `.count()` and `range()` forces us to have a predefined end target, when we really ought to have an open-ended approach: just have a `while` loop that grabs the next chunk by slicing; when a slice/chunk less than chunk size is returned, that's the last iteration, so break out.

However, this doesn't work well for UUIDs as their insertion order is random, as I understand it - meaning, `.order('pk')` will not have the most recent records at the end. In fact, this behaviour means that as new records are added while reindexing, the slice returned will include records processed on previous iterations of the `while`.

If UUID ordering could guarantee that the most recent insertions are at the end, then this approach would be fine. It is almost as if we should have a separate `order_by_field` parameter for this function, like so:
```
def queryset_iterator(queryset, chunksize=1000, order_by_field='pk'):
    if order_by_field:
        queryset = queryset.order_by(order_by_field)

    chunk = 0
    while True:
        n = 0
        for n, row in enumerate(queryset[chunk*chunksize:(chunk+1)*chunksize]):
            yield row
        if not n:
            break
        chunk += 1
        gc.collect()
```
Some further changes would be needed to override the order per `ElasticsearchTypeMixin` handler, but that's trivial. Perhaps not obvious, but the above is completely untested.

I believe this would allow the developer to use the system as is without changes, but also let people having UUID to order their queryset by a `created` or `updated` field if they have one, which would address their particular problem.

Of course, after I wrote the above solution, I have remembered that the `get_queryset()` method on `ElasticsearchTypeMixin` is required, and so the requisite `.order_by()` could simply be placed in there rather than the `order_by_field` change mentioned.

I'd appreciate any thoughts you two might have on this! And better yet, if a pull request could be submitted, better yet.

**Comment by yakky** [comment]
@jaddison thanks for the prompt reply. after a night of sleep you solution it's definitely more complete :)
I have not digged into the perfomance considerations, yet, but any specific reason why the built-in queryset ``iterator()`` is not suitable?

**Comment by jaddison** [comment]
I'd forgotten about .iterator(), although it was definitely considered when I originally wrote this package.

I'm not sure it would yield the performance you're thinking; given https://docs.djangoproject.com/en/1.11/ref/models/querysets/#iterator, it states that "the Python database drivers load the entire result set into memory. The result set is then transformed into Python row objects by the database adapter using the fetchmany() method defined in PEP 249."

I'd have to dig into Django internals, but I think there's a strong possibility that .iterator() would exhaust available memory as well, given a large enough dataset - just not as quickly as normal querysets.

Something to investigate.

**Comment by yakky** [comment]
@jaddison I made some tests with iterator and it delivers roughly the same performance and memory footprint, albeit my dataset is limited (2K objects ~ 20 kb of data each)
I can easily create a much larger dataset based on the same structure, eventually
The code above anyway works well too

**Comment by jaddison** [comment]
I remember using iterator() in my early code, and it's when you get into the hundreds of thousands and millions of records where it becomes a problem, depending on your model structure of course.

I'm almost positive that using iterator() is not the best solution for this problem.

**Comment by yakky** [comment]
@jaddison fair enough. Your proposed solution above works well, anyway.
UUID pk are not the only one we should take into account anyway, thus an explicit order_by is definitely needed

**Comment by jaddison** [comment]
Would appreciate feedback on PR #19. Thanks!
